name: student_project

channels:
- defaults
- conda-forge
- opensourceeconomics

dependencies:
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- statsmodels
- scikit-learn
- pip
- pip:
  - linearmodels
  - scikit-learn


